version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13.2-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: learnwithkru
      RABBITMQ_DEFAULT_PASS: kruIimage
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  gateway:
    container_name: gateway
    build:
      context: ./applications/api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./applications/api-gateway/src:/app/src
    env_file: ./applications/api-gateway/configs/.env
    environment:
      AUTH_SERVICE_URL: http://auth:3001
      TEACHER_SERVICE_URL: "http://teacher:3002"
      STUDENT_SERVICE_URL: "http://student:3003"
      USER_SERVICE_URL: "http://user:3004"
      CLIENT_URL: http://localhost:8000

  notification:
    container_name: notification_container
    build:
      context: ./applications/notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3005:3005"
    volumes:
      - ./applications/notification/src:/app/src
    env_file: ./applications/notification/configs/.env
    environment:
      RABBITMQ_ENDPOINT: amqp://learnwithkru:kruIimage@rabbitmq_container:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  auth:
    container_name: auth
    build:
      context: ./applications/auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./applications/auth/src:/app/src
      - ./applications/auth/public:/app/public
    env_file: ./applications/auth/configs/.env
    environment:
      USER_SERVICE: http://user:3004
      TEACHER_SERVICE: http://teacher:3002
      STUDENT_SERVICE: http://student:3003
      RABBITMQ_ENDPOINT: amqp://learnwithkru:kruIimage@rabbitmq_container:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  user:
    container_name: user
    build:
      context: ./applications/user
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3004:3004"
    volumes:
      - ./applications/user/src:/app/src
      - ./applications/user/public:/app/public
    env_file: ./applications/user/configs/.env
    environment:
      AUTH_SERVICE_GET: http://auth:3001
      TEACHER_SERVICE: http://teacher:3002
      STUDENT_SERVICE: http://student:3003

  student:
    container_name: student
    build:
      context: ./applications/student
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ./applications/student/src:/app/src
      - ./applications/student/public:/app/public
    env_file: ./applications/student/configs/.env
    environment:
      USER_SERVICE: http://user:3004

  teacher:
    container_name: teacher
    build:
      context: ./applications/teacher
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3002:3002"
    volumes:
      - ./applications/teacher/src:/app/src
      - ./applications/teacher/public:/app/public
    env_file: ./applications/teacher/configs/.env
    environment:
      RABBITMQ_ENDPOINT: amqp://learnwithkru:kruIimage@rabbitmq_container:5672
