FROM node:21-alpine3.18

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY private_key.pem ./
COPY public ./public
COPY tsoa.json ./


# Install dependencies and nodemon
RUN npm install && npm install -g nodemon

EXPOSE 3003

CMD ["npm", "run", "start:dev"]
