FROM node:21-alpine3.18

WORKDIR /app

# Copy package.json, tsconfig.json, source code
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY public ./public
COPY tsoa.json ./

# Install dependencies and nodemon
RUN npm install && npm install -g nodemon

EXPOSE 3004

CMD ["npm", "run", "start:dev"]
