# Use the official Node.js image as the base image
FROM node:21-alpine3.18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json  ./
COPY yarn.lock ./
# Install dependencies using Yarn
RUN yarn

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port Next.js is running on (usually 3000)
EXPOSE 3000

# Start the Next.js application
CMD ["yarn", "start", "start:dev"]
