name: CI/CD user Sevice

on:
  push:
    branches:
      - main
    paths:
      - "applications/user/**"

defaults:
  run:
    working-directory: applications/user

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: applications/user/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the Production Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: applications/user/build

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure target directory exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chown ubuntu:ubuntu /home/ubuntu

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "applications/user/build/*"
          target: "/home/ubuntu/"

      - name: Create .env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cat <<EOF > /home/ubuntu/applications/user/build/configs/.env.production
            NODE_ENV=${{ secrets.NODE_ENV }}
            PORT=${{ secrets.USER_PORT }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}
            LOG_LEVEL=${{ secrets.LOG_LEVEL }}
            RABBITMQ_ENDPOINT=${{ secrets.RABBITMQ_ENDPOINT }}
            MONGODB_URL=${{ secrets.USER_MONGODB_URL}}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN}}
            API_GATEWAY=${{secrets.API_GATEWAY}}
            AUTH_SERVICE_GET=${{secrets.AUTH_SERVICE_GET}}
            TEACHER_SERVICE=${{secrets.TEACHER_SERVICE}}
            STUDENT_SERVICE={{secrets.STUDENT_SERVICE}}
            TEST=${{ secrets.TEST }}
            EOF
      - name: Start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            #!/bin/bash

            # Check if nvm is installed
            if [ -s "$HOME/.nvm/nvm.sh" ]; then
              source "$HOME/.nvm/nvm.sh"
            elif [ -s "/usr/local/nvm/nvm.sh" ]; then
              source "/usr/local/nvm/nvm.sh"
            else
              echo "nvm is not installed."
              exit 1
            fi

            # Verify yarn installation
            if ! command -v yarn &> /dev/null; then
              echo "Yarn could not be found"
              exit 1
            fi

            cd /home/ubuntu/applications/user/build
            echo "Checking directory contents..."
            ls -alh # Lists all files in the current directory

            # Check if server.js exists in the correct directory
            if [ ! -f ./src/server.js ]; then
              echo "server.js not found in ./src/"
              exit 1
            fi

            # Install Dependencies
            echo "Installing dependencies..."
            yarn install

            # Check if the PM2 process is running
            if pm2 show user > /dev/null; then
              echo "Application is running. Restarting..."
              yarn restart
            else
              echo "Application is not running. Starting..."
              yarn start
            fi
